### ISSUE TITLE
run test报错

### ISSUE THREAD

**Issue by azl397985856** [ant-tool/atool-test#7]
报错信息如下：

```
throw er; // Unhandled 'error' event
Error: spawn E:\ltcrm\trunk\client\front\node_modules\.bin\karma ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3
```

网上查是端口，但是--port修改端口依然不行

**Comment by silentcloud** [comment]
@azl397985856  windows？这个应该是文件不存在的提示

**Comment by azl397985856** [comment]
是 windows   意思是atool-test模块安装不完全吗

**Comment by silentcloud** [comment]
@azl397985856 windows 环境不是太熟，我搜了一下，应该是环境变量的问题

**Comment by sorrycc** [comment]
`E:\ltcrm\trunk\client\front\node_modules\.bin\karma` windows 是应该不是这种路径，貌似是 `xxx.cmd` 这种格式的。
